### ISSUE TITLE
ply not compiling on linux <v5.5 because of BPF_FUNC_probe_read_kernel

### ISSUE THREAD

**Issue by it-klinger** [wkz/ply#37]
When compiling with a kernel version < v5.5 it fails with:

ir.c: In function 'ir_emit_read_to_sym':
ir.c:419:31: error: 'BPF_FUNC_probe_read_kernel' undeclared (first use in this function); did you mean 'BPF_FUNC_probe_read_str'?
  419 |         ir_emit_insn(ir, CALL(BPF_FUNC_probe_read_kernel), 0, 0);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~

Looking at the linux repo it turned out that the function 'bpf_probe_read_kernel' where introduced with commit 6ae08ae3dea2cfa03dd3665a3c8475c2d429ef47 ("bpf: Add probe_read_{user, kernel} and probe_read_{user, kernel}_str helpers") into the kernel.

**Comment by it-klinger** [comment]
I just read that Linux <= 5.5 is required. Sorry for the spam.

**Comment by wkz** [comment]
No worries.

Unless you're running on either RISC-V or MIPS, 2.2.0 should be functionally equivalent to `master` - and work on older kernels.
